site_name: "Learn LabVIEW"
site_description: 
site_author: 
copyright:
repo_url: 

nav:
  - Home: index.md
  - Contents:
    - LabVIEW 编程基础: basics/


plugins:
  - search
  - macros
  - print-site

extra_css: 
  - css/extra.css

extra_javascript:
  - js/extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
theme:
  name: mkdocs
  palette:
    primary: blue grey
  font:
    code: Noto Sans Simplified Chinese
  features:
    - search.suggest
    - search.highlight
  highlightjs: true
  hljs_languages: # rg '^```\w+' | sed 's/.*:```\(\w*\)/    - \1/g' | sort | uniq
    - bash
    - c
    - cmake
    - cpp
    - diff
    - java
    - json
    - llvm
    - nasm
    - python
    - rust
    - txt
markdown_extensions:
  - extra
  - tables
  - toc
  - fenced_code
  - sane_lists
  - smarty
  - pymdownx.arithmatex
