site_name: "Learn LabVIEW"
site_description: "我和LabVIEW的拆书记录"
site_author: "王国梁"
repo_url: "http://www.ccwanggl.com"

nav:
  - 前言: index.md
  - LabVIEW 编程基础: 
    - 数值和布尔数据: basics/data_number.md
    - 数组和循环结构: basics/data_array.md
    - 字符串和路径数据: basics/data_string.md


plugins:
  - search
  - macros
  - print-site

extra_css: 
  - stylesheet/extra.css

extra_javascript:
  - javascripts/extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

theme:
  name: material
  palette:
    primary: blue grey
  font:
    code: Noto Sans Simplified Chinese
  features:
    - search.suggest
    - search.highlight
  highlightjs: true
  hljs_languages: # rg '^```\w+' | sed 's/.*:```\(\w*\)/    - \1/g' | sort | uniq
    - bash
    - c
    - cmake
    - cpp
    - diff
    - java
    - json
    - llvm
    - nasm
    - python
    - rust
    - txt
markdown_extensions:
  - extra
  - tables
  - toc
  - fenced_code
  - sane_lists
  - smarty
  - pymdownx.arithmatex
